graph LR

  A[Attitude toward the act]-->D[Behavioural Intention]
  B[Subjective Norm]-->D[Behavioural Intention]
  C[Perceived Behavioural Control]-->D[Behavioural Intention]
  D[Behavioural Intention]-->E[Behaviour]
  C[Perceived Behavioural Control]-.->E[Behaviour]
  
  classDef className fill:red,stroke:#333,stroke-width:4px;
  class A,B,C,D className;
",  height = '100%', width = '100%')